[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hermite_function"
version = "0.0.1"
authors = [
  { name="Sebastian Gössl", email="goessl@student.tugraz.at" },
]
description = "A Hermite function series module."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/goessl/hermite_function"
"Bug Tracker" = "https://github.com/goessl/hermite_function/issues"
